### ISSUE TITLE
Not able to access paragraphs data

### ISSUE THREAD

**Issue by LarssonHenrik** [chapter-three/next-drupal#236]
Hi, first and foremost, thanks for a great integration with Drupal!

We're trying this out and we're running into issues when trying to populate [paragraphs](https://www.drupal.org/project/paragraphs) data to our basic pages.

In `[...slug].tsx` we're including `field_content` which holds all our paragraphs:

```
if (type === "node--page") {
  params = {
    include: "field_content",
  }
}
```

When we console.log our `response` (the entire node data) we can see that there is a paragraph called `paragraph--hero` which is good. But we can't access the data nested inside the paragraph:

![CleanShot 2022-06-20 at 08 16 19@2x](https://user-images.githubusercontent.com/37071548/174537398-72d98b07-0112-4e4a-9f6d-636878e15c0c.png)

When we check our api-response locally (`http://localhost/jsonapi/node/page?include=field_content`), we can see that our  nested paragraph data lives inside the `included` part of the response:

![CleanShot 2022-06-20 at 08 13 36@2x](https://user-images.githubusercontent.com/37071548/174537634-46b3c92a-4216-4f44-8d4f-530e9018db87.png)

Sadly the `included` part is not available to us when we console log the entire node data:

![CleanShot 2022-06-20 at 08 23 55@2x](https://user-images.githubusercontent.com/37071548/174538154-731280b8-6138-4d96-aad3-301c1f4d1f79.png)

Does anyone have a solution or know how to access the nested data? We need this to be able to build dynamic pages.

**Comment by shadcn** [comment]
Hi.

What's under attributes here?

![174537634-46b3c92a-4216-4f44-8d4f-530e9018db87](https://user-images.githubusercontent.com/124599/174539790-9a63e1d4-4173-4c2b-9de2-28a1e6e8d9cd.png)

What are the fields under the hero paragraph?

**Comment by LarssonHenrik** [comment]
Hi, thanks for the quick answer :)

Below `attributes` we have:

![CleanShot 2022-06-20 at 08 42 49@2x](https://user-images.githubusercontent.com/37071548/174540878-2bbe86e1-a7a7-4b12-b1cf-47abf1a84292.png).

So far we've only added fields for a title, preamble and an image.

**Comment by shadcn** [comment]
Hmm yeah you should've the `field_preamble` and `field_title` in the hero paragraph. Let's see...

The fields are visible when you visit `http://localhost/jsonapi/node/page?include=field_content` un-authenticated?

**Comment by LarssonHenrik** [comment]
They are visible below `included` but not below `data.attributes`:

<img width="2304" alt="CleanShot 2022-06-20 at 09 03 23@2x" src="https://user-images.githubusercontent.com/37071548/174544420-d6107370-330b-4c35-bc76-1d7d39bd3696.png">

I know we have bumped into something similar before while trying decoupled where we had to access the `included` part to get all the data from our paragraphs, when we looped through the paragraphs we looped the `included` array:

Our API call was something similar to this:
`http://localhost/jsonapi/node/page?include=field_content.field_image,field_content.field_title`

{page.included.map((component) => (
  <div key={component.id}>
    <DynamicContent
       content={page.included}
       component={component}
    />
  </div>
))}

But if I'm trying to include `included` in our params I get an error:

`Error: 400 Bad Request
`included` is not a valid relationship field name. Possible values: node_type, revision_uid, uid, menu_link, field_content`

```
if (type === "node--page") {
    params = {
      include: "field_content,included",
    }
  }
```
<img width="2304" alt="CleanShot 2022-06-20 at 09 13 16@2x" src="https://user-images.githubusercontent.com/37071548/174545407-08015be6-a3b0-44d7-8da5-d83cf572eb6b.png">

**Comment by shadcn** [comment]
You can chain the nested includes like this:

```
if (type === "node--page") {
  params = {
    include: "field_content.field_image,field_content.field_title", // <----- dot notation, comma-separated, no space.
  }
}
```

**Comment by LarssonHenrik** [comment]
Yep we've tried that but then the following error occurs:

`Error: 400 Bad Request
'field_content.field_title' is not a valid include path. 'field_title' is not a valid relationship field name. Possible values: paragraph_type, field_image.`

**Comment by shadcn** [comment]
Yeah that's because `field_title` is not an entity reference field. Is `field_image` coming through?

**Comment by LarssonHenrik** [comment]
Aa got it!

No unfortunately not, still get the same result as before with:

```
if (type === "node--page") {
  params = {
    include: "field_content.field_image",
}
```
 
<img width="2304" alt="CleanShot 2022-06-20 at 09 37 28@2x" src="https://user-images.githubusercontent.com/37071548/174549548-89e4d358-6b12-442d-9329-1f29e731faeb.png">

**Comment by shadcn** [comment]
@LarssonHenrik can you share the whole code please? Including the part where the fetch call is made with the params. Thank you.

I've also tried to reproduce this. I have a drupal site set up here: https://dev-next-drupal.pantheonsite.io/jsonapi/node/landing_page/1f46f892-aaaa-45cd-b8d4-dee422e65530

This is a **`node--landing_page` with a paragraphs field named `field_sections`**.

This is how I'm including it:

```ts
{
      params: {
        include: "field_sections"
      }
    }
```

Here's the codesandbox: https://codesandbox.io/s/epic-lake-nsu1nv?file=/pages/index.tsx

**Comment by LarssonHenrik** [comment]
I also tested to copy you `index.tsx` code but ended up with the same result, no paragraph fields data available, maybe it has got to do with authentication or something?

**Comment by shadcn** [comment]
@LarssonHenrik The code looks good. 

If the fields are visible when you visit http://localhost/jsonapi/node/page?include=field_content un-authenticated, then `next-drupal` should be able to access it.

Is the site available online where I can try debug this?

You can also DM me directly on Drupal Slack.

**Comment by LarssonHenrik** [comment]
Hi again @shadcn!

I continued to investigate this yesterday and it seems like I hadn't configured the module `Paragraphs Type Permissions` properly.

After I configured that anonymous users would be able to view my Hero paragraph, the data is now showing up in my response.

<img width="1325" alt="CleanShot 2022-06-21 at 07 57 42@2x" src="https://user-images.githubusercontent.com/37071548/174726711-9eb9fad1-156e-4429-bf56-c90d54662853.png">

Thanks for all your help and feedback!

**Comment by simon-olsen** [comment]
Just dropping this here in case anyone else needs help with this. I don't have any Paragraph Type permissions added to my Drupal site. I was able to access my Paragraph and the Media asset within it with the following:

My paragraphs field is **Body variation** with a Paragraph Type of **Image and body text** which has an image, a select field for image position (above, left or right) and the _Body continued_ field.

For the `include` on  my `node--article` type in `getStaticProps`
```
if (type === "node--article") {
    params = {
      include:
        "field_body_variation.field_image_asset.field_media_image,uid",
    };
  }
```

This gives me all three fields in my response. If I just add `field_body_variation` without the `.field_image_asset.field_media_image` I'm not able to see the path to the asset in the Media Library in my response.
```
field_body_continued:
    format: "basic_html"
    processed: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et fermentum dui. Ut orci quam, ornare sed lorem sed, hendrerit auctor dolor. Nulla viverra, nibh quis ultrices malesuada, ligula ipsum vulputate diam, aliquam egestas nibh ante vel dui. Sed in tellus interdum eros vulputate placerat sed non enim. Pellentesque eget.</p>\n"
    value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et fermentum dui. Ut orci quam, ornare sed lorem sed, hendrerit auctor dolor. Nulla viverra, nibh quis ultrices malesuada, ligula ipsum vulputate diam, aliquam egestas nibh ante vel dui. Sed in tellus interdum eros vulputate placerat sed non enim. Pellentesque eget.</p>\r\n"
field_image_asset:
    field_media_image:
        changed: "2022-08-03T10:45:37+00:00"
        created: "2022-08-03T10:45:23+00:00"
        resourceIdObjMeta: {alt: 'Photograph of Australian outback', title: null, width: 4608, height: 3072, drupal_internal__target_id: 5}
        uri: {value: 'public://2022-08/pexels-pixabay-162379-small.jpg', url: '/sites/bradhazzard/files/2022-08/pexels-pixabay-162379-small.jpg'}
field_image_position: "above"
```

I got stuck on this while trying to use Paragraphs that use Media assets (as opposed to a simple Image field). Hope this helps someone.
