### ISSUE TITLE
Register site preview as a node operation

### ISSUE THREAD

**Issue by mandclu-acquia** [chapter-three/next-drupal#463]
Having the site preview is an excellent capability, but it's unfortunate that you can't access it directly for nodes when you're view the site's content at /admin/content . As a content editor, I would like to see the preview without having to click to the edit form first.

I was able to get this working with just a little extra code:

First, add to next.module:
```
/**
 * Implements hook_entity_type_build().
 */
function next_entity_type_build(array &$entity_types) {
  // @todo make this work for toher entity types?
  $entity_type_id = 'node';
  $entity_types[$entity_type_id]->setLinkTemplate('site-preview', "/$entity_type_id/{{$entity_type_id}}/site-preview");
}

/**
 * Declares entity operations.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity on which the linked operations will be performed.
 *
 * @return array
 *   An operations array as returned by
 *   EntityListBuilderInterface::getOperations().
 *
 * @see \Drupal\Core\Entity\EntityListBuilderInterface::getOperations()
 */
function next_entity_operation(EntityInterface $entity) {
  if ($entity->hasLinkTemplate('site-preview')) {
    // ddl($entity);
    return [
      'clone' => [
        'title' => t('Preview'),
        'weight' => 40,
        'url' => $entity->toUrl('site-preview'),
      ],
    ];
  }
```

Then add to next.routing.yml:
```
entity.node.site_preview:
  path: '/node/{node}/site-preview'
  defaults:
    _title: 'Preview'
  requirements:
    node: \d+
  options:
    _node_operation_route: TRUE
    parameters:
      node:
        type: entity:node
```

I deliberately wrote these changes specifically for nodes, but they could be altered to work with other entities, not really sure what everyone needs to preview this way. If there's agreement that this worthwhile I'd be happy to submit the above as a PR.
