### ISSUE TITLE
Add Drupal 10.2/PHP 8.3 to CI matrix

### ISSUE THREAD

**Issue by JohnAlbin** [chapter-three/next-drupal#542]
Drupal 9.5 becomes unsupported when D10.2 is released in December 2023. And PHP 8.3 support [has been added to D10.2](https://www.drupal.org/project/drupal/issues/3366286).

```
php: ["8.1", "8.2", "8.3"]
drupal: ["10.0", "10.1", "10.2"]
exclude:
  - php: "8.3"
    drupal: "10.0"
  - php: "8.3"
    drupal: "10.1"
```
